make clientid configurable
john30/ebusd pull request #226
Opened 2018-11-15 08:20 UTC by teichsta

Hi,

this is a PR according to the discussion in #223. Please forgive that i never wrote C code so this one mainly is copy pasting code. I am also not sure about the variable assignment in L363.

It would be great if you could have a look and probably merge this one quickly as i am currently stuck and i hope to get your feedback on this soon.

Thanks a lot, Thomas E.-E.

2018-11-15 10:07 UTC, andig commented on src/ebusd/mqtthandler.cpp
> +#define O_CLID (O_KEYF+1)
O_KEYF+1 looks wrong and is a duplicate ;)

2018-11-15 13:34 UTC, andig commented on src/ebusd/mqtthandler.cpp
> +    if (arg == nullptr) {
Just guessing, but maybe add 

    || arg[0] == 0

to check for 0 length, same as O_TOPI?

2018-11-19 09:08 UTC, teichsta commented
@john30 any chance to look into this PR?

2018-11-20 14:44 UTC, john30 commented
Not this week

2018-11-21 09:23 UTC, teichsta commented
> Not this week

ok, got the code running on my machine, so no worries. I also added an option to set MQTT protocol version to 3.1.1. With this setup i am able to connect ebusd to Google Cloud IoT Core. It would be great to add a function to generate the JWT token to improve the authentication bit.

2018-11-21 09:44 UTC, andig commented
> It would be great to add a function to generate the JWT token to improve the authentication bit.

Why should that be ebusd responsibility?

2018-11-23 16:01 UTC, teichsta commented
> Why should that be ebusd responsibility?
because ebusd (in this case) acts as a MQTT client which needs to authenticate against a broker. There are several authentication mechanisms and one of which is JWT. Another is user/password which also is supported.

2018-11-26 16:46 UTC, john30 commented
does not work this way for backwards compatibility

2018-11-27 08:58 UTC, andig commented
> does not work this way for backwards compatibility

@john30: was this comment potentially meant for https://github.com/john30/ebusd/issues/219?

2018-11-27 09:03 UTC, john30 commented
@andig no for this one, as Travis CI build has failed

2018-11-27 12:28 UTC, andig commented
@teichsta could you take a look? MQTT 3.1.1 doesn't compile:

    mqtthandler.cpp: In constructor ‘ebusd::MqttHandler::MqttHandler(ebusd::UserInfo*, ebusd::BusHandler*, ebusd::MessageMap*)’:
    mqtthandler.cpp:398:33: error: ‘MQTT_PROTOCOL_V311’ was not declared in this scope
        int mqttProtocolVersion = MQTT_PROTOCOL_V311;
                                    ^
    mqtthandler.cpp:400:43: error: ‘MOSQ_OPT_PROTOCOL_VERSION’ was not declared in this scope
        if (mosquitto_opts_set(m_mosquitto, MOSQ_OPT_PROTOCOL_VERSION, &mqttProtocolVersion) != MOSQ_ERR_SUCCESS) {
                                            ^
    mqtthandler.cpp:400:90: error: ‘mosquitto_opts_set’ was not declared in this scope
        if (mosquitto_opts_set(m_mosquitto, MOSQ_OPT_PROTOCOL_VERSION, &mqttProtocolVersion) != MOSQ_ERR_SUCCESS) {
                                
Maybe split that into a separate PR?

2018-11-28 10:04 UTC, teichsta commented
> Maybe split that into a separate PR?

yes, reverted this MQTT v3.1.1 switch and create another PR for this!

2018-11-30 06:37 UTC, john30 requested changes

2018-11-30 06:37 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +  {"mqttclientid", O_CLID, "CLIENTID",    0, "Set the MQTT CLIENTID, defaults to PACKAGE_NAME_PACKAGE_VERSION_PID", 0 },
rather:
"Set the MQTT CLIENTID [" PACKAGE_NAME "_" PACKAGE_VERSION "_<pid>]"

2018-11-30 06:37 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +static const char* g_clientId = nullptr;  //!< optional clientid, defaults to PACKAGE_NAME_PACKAGE_VERSION_PID
rather:
optional clientid [PACKAGE_NAME '_' PACKAGE_VERSION '_' <pid>]

2018-11-30 06:37 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +    if (arg == nullptr) {
also check length > 0

2018-12-02 11:45 UTC, closed without merging