introduced configurable mqtt protocol version
john30/ebusd pull request #227
Opened 2018-11-28 10:14 UTC by teichsta

2018-11-28 10:28 UTC, teichsta commented
interestingly the build is working locally (on my RPi) and fails with 

`mqtthandler.cpp: In constructor ‘ebusd::MqttHandler::MqttHandler(ebusd::UserInfo*, ebusd::BusHandler*, ebusd::MessageMap*)’:
mqtthandler.cpp:398:33: error: ‘MQTT_PROTOCOL_V311’ was not declared in this scope
    int mqttProtocolVersion = MQTT_PROTOCOL_V311;
                                ^
mqtthandler.cpp:400:43: error: ‘MOSQ_OPT_PROTOCOL_VERSION’ was not declared in this scope
    if (mosquitto_opts_set(m_mosquitto, MOSQ_OPT_PROTOCOL_VERSION, &mqttProtocolVersion) != MOSQ_ERR_SUCCESS) {
                                        ^
mqtthandler.cpp:400:90: error: ‘mosquitto_opts_set’ was not declared in this scope
    if (mosquitto_opts_set(m_mosquitto, MOSQ_OPT_PROTOCOL_VERSION, &mqttProtocolVersion) != MOSQ_ERR_SUCCESS) {`

on Travis … can this be due to a different version of libmosquitto?

2018-11-28 10:35 UTC, john30 commented
> on Travis … can this be due to a different version of libmosquitto?

definitely. you need to check the libmosquitto version for availablility of the used function and defines. furthermore, I'd rather use something like `--mqttversion=311` to be more flexible for future versions

2018-11-30 06:33 UTC, john30 requested changes

2018-11-30 06:33 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +#define O_V311 (O_JSON+1)
rather O_VERS

2018-11-30 06:33 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +  {"mqttv311",     O_V311, nullptr,       0, "Use MQTT protocol 3.1.1 rather than 3.1", 0 },
rather mqttversion with "VERSION" as int
"Use MQTT protocol VERSION instead of library default"

2018-11-30 06:33 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +static bool g_isMqttV311 = false;
int g_mqttVersion

plus for all version related stuff:
#if ((LIBMOSQUITTO_MAJOR > 3) || ((LIBMOSQUITTO_MAJOR == 3) && ((LIBMOSQUITTO_MINOR > 1) || ((LIBMOSQUITTO_MINOR == 1) && (LIBMOSQUITTO_REVISION >= 1)))))
...
#endif

2018-11-30 06:33 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +    g_isMqttV311 = true;
parse int and check if >=310

2018-11-30 06:33 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +    if (g_isMqttV311) {
g_mqttVersion > 0

2018-11-30 06:33 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +      int mqttProtocolVersion = MQTT_PROTOCOL_V311;
remove

2018-11-30 06:33 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +      if (mosquitto_opts_set(m_mosquitto, MOSQ_OPT_PROTOCOL_VERSION, &mqttProtocolVersion) != MOSQ_ERR_SUCCESS) {
g_mqttVersion instead of mqttProtocolVersion

2018-11-30 06:33 UTC, john30 commented on src/ebusd/mqtthandler.cpp
> +          logOtherError("mqtt", "unable to set MQTT protocol version, defaulting to V31");
logOtherError("mqtt", "unable to set desired MQTT protocol version");

2018-12-28 06:59 UTC, john30 commented
solved with cb78d981857d4315bfb3568ffcab1c0b1452f534

2018-12-28 06:59 UTC, closed without merging